packages:
  - packages/*
  - scripts
  - examples/*
  - vendor/*

catalog:
  '@bomb.sh/tty': '^0.8.0'
  '@bomb.sh/args': '^0.3.1'
  '@clack/ui': 'https://pkg.pr.new/bombshell-dev/ui/@clack/ui@a60ac12'
  '@clack/prompts': '^1.7.0'
